# Generated by Django 4.0.6 on 2024-04-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenhando', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='isbn',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='usuario',
            field=models.CharField(max_length=45),
        ),
    ]
